### ISSUE TITLE
Can't Load Plugin

### ISSUE THREAD

**Issue by Novum-Semita** [Sythelux/TerrainPlugin#1]
**Describe the bug**
When I try to load the plugin in the Plugins tab I get the following message: "Unable to load addon script from path: 'res://addons/TerrainPlugin/TerrainPlugin.cs'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/TerrainPlugin/plugin.cfg' to prevent further errors."

**To Reproduce**
1. Go to 'Project Settings"
2. Try to load the plugin. 
3. See error.

**Expected behavior**
The plugin should load without errors.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 114.0.5735.199
 - Godot Version 4.0.3

**Comment by thisisjamaldin** [comment]
any news?

**Comment by Sythelux** [comment]
Hello, please read the the getting-started in the upstream wiki: https://github.com/sboron/terrain-tool-godot4/wiki/getting-started

I'll merge my recent changes to sboron upstream and will delete issues here soon, to improve development. 

If the error continues to happen after following the guide, please open a ticket there.
